### ISSUE TITLE
Support the raspberry pi 4?

### ISSUE THREAD

**Issue by rcla** [schnitzeltony/meta-raspi-light#4]
Is there a possibility to support the raspberry pi 4?

**Comment by schnitzeltony** [comment]
Honestly I don't know.: Don't have a Rpi4 yet (maybe I get one Christmas..).
And meta-raspberrypi has a 4.19 rt-kernel these days that I would like to give it a try - but that is not my top priority.

**Comment by rcla** [comment]
Ok. I understand.
Thank you

**Comment by schnitzeltony** [comment]
Month later: Done.
